name: ballerina-dependabot
author: TharindaDilshan
description: Dependency updater for Ballerina 

inputs: 
  git_email:
    description: 'The email pull request should be associated with'
    required: true
  git_username:
    description: 'The name pull request should be associated with'
    required: true
  token:
    description: 'GitHub token used to open pull requests'
    required: true
  file_path:
    description: 'Path to the Ballerina.toml file'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  
branding:
  icon: 'bold'
  color: 'gray-dark'
