name: Test
on: 
  workflow_dispatch:
  schedule:
        - cron: '30 18 * * 7'
jobs:
  resolve_dependencies:
    runs-on: ubuntu-latest
    name: Dependabot
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dependabot Action
        uses: ./
        with:
          git_email: ${{ secrets.BALLERINA_BOT_EMAIL }}
          git_username: ${{ secrets.BALLERINA_BOT_USERNAME}}
          token: ${{ secrets.BALLERINA_BOT_TOKEN }}
          file_path: test/
